### ISSUE TITLE
更新最新代码后运行报错

### ISSUE THREAD

**Issue by jiezaizone** [Bespertrijun/PrettyServer#4]
<img width="949" alt="image" src="https://github.com/Bespertrijun/PrettyServer/assets/28976666/d63c7f31-8c25-493c-aaa1-1752cfcf2b14">
更新最新代码后，仅改了plex1的url、token，Env中的tmdb_api参数，然后运行错误，错误如下
<img width="1132" alt="image" src="https://github.com/Bespertrijun/PrettyServer/assets/28976666/1601d6c8-0df6-4238-9766-62ab6b56989e">
检查url、token数据没有错误，在上一个版本是可以运行的

**Comment by Bespertrijun** [comment]
若报错aiohttp.client_exceptions.InvalidURL: xxx/library/sections/ 请在配置文件中删除你不需要的服务器 
希望能解决你的问题
